Update WASI interface and add integration test with sdf-viewer-go

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,6 +32,29 @@ jobs:
         run: |
           cargo test --features "app server sdfdemo meshers" --lib # Test different feature combinations?
 
+      - name: Integration test with sdf-viewer-go
+        run: |
+          # Start the app for the latest wasm generated
+          # If the app did not log any errors and is running after N seconds, then the test is successful
+          cargo run --features "app server sdfdemo meshers" --  app url https://yeicor.github.io/sdf-viewer-go/sdf-viewer-go-sdfx.wasm >app.log &
+          
+          # Print the app log while the app is running
+          timeout 30s tail -f app.log || echo "Stopping and checking app.log for errors..."
+          # Kill the app that was running in the background
+          kill %1
+          
+          # Check for errors
+          if grep -i -q "error" app.log; then
+            echo "> Error found in app.log"
+            exit 1
+          fi
+          
+          # Check that the app finished loading... (2 times as it loads the demo first)
+          if [ $(grep -i "Loaded last" app.log | wc -l) -lt 2 ]; then
+            echo "> App did not finish loading"
+            exit 1
+          fi 
+
       - run: rustup component add clippy # rustfmt
       - name: Install clippy extras
         run: cargo install clippy-sarif sarif-fmt
